#! /bin/bash
#Launch an instance with 9000 and t2.medium
cd /opt/
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.2.0.77652.zip
unzip sonarqube-10.2.0.77652.zip
amazon-linux-extras install java-openjdk11 -y
useradd sonar
chown sonar:sonar sonarqube-10.2.0.77652 -R
chmod 777 sonarqube-10.2.0.77652 -R
su - sonar
cd /opt
cd sonarqube-10.2.0.77652/bin/linux/
./sonar.sh start
./sonar status

#run this on server manually
#sh /opt/sonarqube-8.9.6.50800/bin/linux-x86-64/sonar.sh start
#echo "user=admin & password=admin
